name: SMSML_M-DAFFA-YUNUS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "https://raw.githubusercontent.com/Daffdhot29/SMSML_M-Daffa-Yunus/main/membangun_model/data_preprocessing.csv"
  TARGET_VAR: "Churn"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r membangun_model/requirements.txt

      - name: Run modelling script
        run: |
          python membangun_model/modelling.py
